enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
max_width = 120
merge_imports = true
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
