[package]
name = "lancelot"
description = "binary analysis framework for x32/x64 PE files"
license = "Apache-2.0"
version = "0.6.0"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2018"

[badges]
travis-ci = { repository = "https://github.com/williballenthin/lancelot", branch = "master" }

[dependencies]
log = "0.4"
goblin = "0.4"
zydis = "3"
byteorder = "1"
bitflags = "1"
lazy_static = "1"
fern = "0.6"
chrono = "0.4"
anyhow = "1"
thiserror = "1"
regex = "1"
smallvec = "1"
widestring = "0.4"
smol_str = "0.1"
bitvec = "0.20"

# https://github.com/myrrlyn/funty/issues/3#issuecomment-778629965
funty="=1.1.0"

lancelot-flirt = { path = "../flirt", version = "0.6.0" }

[dev-dependencies]
criterion = "0.3"
# while there is a newer unicorn-rs release (0.9.1)
# it doesn't build the underlying `unicorn` library transparently.
# so we use 0.8 that will do it for us.
#
# the upstream unicorn/next branch maintains rust bindings,
# but they're not published yet.
unicorn = "0.8.0"
dynasm = "1.0.1"
dynasmrt = "1.0.1"

[[bench]]
name = "emu"
harness = false

[features]
# The reason we do this is because doctests don't get cfg(test)
# See: https://github.com/rust-lang/cargo/issues/4669
test = []