[package]
name = "flirt"
version = "0.1.0"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
nom = "5"
regex = "1.3"
failure = "0.1.8"
bitvec = "0.17"
clap = "2.33"
fern = "0.5"
chrono = "0.4"
better-panic = "0.2"
bitflags = "1"
inflate = "0.4"
