[package]
name = "pylancelot"
version = "0.1.0"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2018"

[lib]
name = "pylancelot"
crate-type = ["cdylib"]

[dependencies]
lancelot = { path = "../core" }
pyo3 = { version = "0.8.1"}
failure = "0.1.5"
zydis = { git = "https://github.com/zyantific/zydis-rs", rev="c4474211863004ce87464a2ea397341b7e1a6b6f", features=["serialization"]}

[features]
# see: https://github.com/PyO3/pyo3/issues/340
# see: https://github.com/bytecodealliance/wasmtime/issues/468
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

