on: [push, pull_request]

name: build

jobs:
  whl:
    name: build python wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: build wheels
        run: |
          docker run --rm -v $(pwd):/io --workdir=/io williballenthin/maturin build --release --strip --manifest-path=./pylancelot/Cargo.toml --manylinux 2010
      
      - uses: actions/upload-artifact@v2
        with:
          name: whl
          path: target/wheel
