on: [push, pull_request]

name: build

jobs:
  whl:
    name: build python wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: build wheels
        run: |
          docker run --rm -v $(pwd):/io konstin2/maturin build --release --strip --manifest-path=./pylancelot/Cargo.toml
