on: [push, pull_request]

name: build

jobs:
  whl:
    name: build python wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: build wheels
        run: |
          docker run --rm -v $(pwd):/io --workdir=/io williballenthin/maturin build --release --strip --manifest-path=./pylancelot/Cargo.toml --manylinux 2010
      
      - uses: actions/upload-artifact@v2
        with:
          name: pylancelot-0.1.0-cp35-cp35m-manylinux2010_x86_64.whl
          path: target/wheels/pylancelot-0.1.0-cp35-cp35m-manylinux2010_x86_64.whl
      - uses: actions/upload-artifact@v2
        with:
          name: pylancelot-0.1.0-cp36-cp36m-manylinux2010_x86_64.whl
          path: target/wheels/pylancelot-0.1.0-cp36-cp36m-manylinux2010_x86_64.whl
      - uses: actions/upload-artifact@v2
        with:
          name: pylancelot-0.1.0-cp37-cp37m-manylinux2010_x86_64.whl
          path: target/wheels/pylancelot-0.1.0-cp37-cp37m-manylinux2010_x86_64.whl
      - uses: actions/upload-artifact@v2
        with:
          name: pylancelot-0.1.0-cp38-cp38-manylinux2010_x86_64.whl
          path: target/wheelspylancelot-0.1.0-cp38-cp38-manylinux2010_x86_64.whl
 
