on: [pull_request]

name: CI

jobs:
  check:
    name: check
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: test core
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p lancelot
      - name: test flirt
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p flirt
      - name: test pylancelot
        working-directory: ./pylancelot/
        run: |
          sudo apt-get install -y build-essential gcc cmake python3.8 python3.8-dev virtualenv
          mkdir /tmp/vdir
          virtualenv -p python3.8 /tmp/vdir
          source /tmp/vdir/bin/activate
          pip install -U pip setuptools maturin pytest pefile
          maturin develop
          pytest
  build:
    name: build
    runs-on: ubuntu-latest
    #needs: [check, clippy, test]
    needs: []
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.1-manylinux2010_x86_64
        with:
          python-versions: 'cp38-cp38m'
          build-requirements: 'maturin'
          pre-build-command: 'bash .github/workflows/build-pylancelot.sh'
          pip-wheel-args: '--help'
