on: [pull_request]

name: CI

jobs:
  check:
    name: check
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: test core
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p lancelot
      - name: test flirt
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p flirt
      - name: test pylancelot
        working-directory: ./pylancelot/
        run: |
          sudo apt-get install -y build-essential gcc cmake python3.8 python3.8-dev virtualenv
          mkdir /tmp/vdir
          virtualenv -p python3.8 /tmp/vdir
          source /tmp/vdir/bin/activate
          pip install -U pip setuptools maturin pytest pefile
          maturin develop
          pytest
